"use client";

import { useState } from "react";
import styles from "./assignments.module.css";

type Tab = "file" | "text" | "link";

export default function Assignments() {
  const [tab, setTab] = useState<Tab>("file");

  return (
    <main className={styles.page}>
      <div className={styles.header}>
        <h1>assignment</h1>
        <a className={styles.linkBtn} href="#">request regrade</a>
      </div>

      <div className={styles.row}>
        <section className={styles.left}>
          <div className={styles.sectionTitle}>submission</div>

          <div className={styles.tabs}>
            <button
              className={`${styles.tab} ${tab === "file" ? styles.active : ""}`}
              onClick={() => setTab("file")}
            >
              file
            </button>
            <button
              className={`${styles.tab} ${tab === "text" ? styles.active : ""}`}
              onClick={() => setTab("text")}
            >
              text
            </button>
            <button
              className={`${styles.tab} ${tab === "link" ? styles.active : ""}`}
              onClick={() => setTab("link")}
            >
              link
            </button>
          </div>

          {/* generated by chatgpt 
          unsure of how to implement a file select*/}
          {tab === "file" && (
            <label className={styles.box}>
              <input type="file" className={styles.hidden} />
              <span>upload file</span>
            </label>
          )}

          {/* generated by chatgpt 
          shows <textarea> when text tab is selected */}
          {tab === "text" && (
            <textarea className={styles.box} placeholder="type here..." />
          )}
          {tab === "link" && (
            <input className={styles.box} type="url" placeholder="https://..." />
          )}
        </section>

        <aside className={styles.right}>
          <div className={styles.sectionTitle}>location</div>
          <div className={styles.smallBox}>
            course: CS 2510
            <br />
            section: A
            <br />
            due: Sep 20, 11:59pm
          </div>
        </aside>
      </div>

      <div className={styles.footer}>
        <button className={styles.primary}>submit/review</button>
      </div>
    </main>
  );
}
